spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ibyacu_db
    username: descholar
    password: Mugirase1.

  jpa:
    hibernate-ddl-auto: none
    generate-ddl: true
    show-sql: true