export const GET_ERRORS = "GET_ERRORS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_BY_USER_ID = 'GET_USER_BY_USER_ID'
export const ADD_STORY = "ADD_STORY";
export const UPDATE_NUMBER_OF_VIEWS = "UPDATE_NUMBER_OF_VIEWS";
export const DELETE_STORY = "DELETE_STORY";
export const ADD_DRAFT = "ADD_DRAFT";
export const GET_ALL_STORIES = "GET_ALL_STORIES";
